language: go

go:
  - 1.13.x

  
addons:
  sonarcloud:
    organization: "aurelienspnll-github"
    token:
      secure: "90c76f94bae85b2120a74d5bb5992e9e0dcfec95"
      
install:
  # Installs Go Meta Linter (Golint and Go vet are also supported independently)
  - go get -u gopkg.in/alecthomas/gometalinter.v2
  - $GOPATH/bin/gometalinter.v2 --install

before_script:
  - go get github.com/aurelienspnll/tic-tac-toe/
  - go get github.com/stretchr/testify/assert

# Don't email me the results of the test runs.
notifications:
  email: false

script:
  # Execute Go Meta Linter
  - $GOPATH/bin/gometalinter.v2 samples/ > gometalinter-report.out || true
  # Execute tests and coverage
  - go test ./test/ -json > report.json
  - go test ./test/ -coverprofile=coverage.out
  # And then execute SonarCloud analysis which will run its own code analysis, and also reuse the linters' results
  - sonar-scanner