language: go

go:
  - 1.13.x

before_script:
  - go get github.com/aurelienspnll/tic-tac-toe/

# Don't email me the results of the test runs.
notifications:
  email: false

script:
  - go test -v ./test/